# Docker Compose для локальной разработки
# Включает все сервисы приложения с hot-reload и инструменты для разработки

version: '3.8'

services:
  # ==============================================
  # Инфраструктурные сервисы
  # ==============================================

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: znak-lavki-postgres-dev
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-znak_lavki}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - znak-lavki-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: znak-lavki-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - znak-lavki-network

  # MinIO S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: znak-lavki-minio-dev
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - znak-lavki-network

  # MinIO Client для инициализации buckets
  minio-init:
    image: minio/mc:latest
    container_name: znak-lavki-minio-init-dev
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin};
      /usr/bin/mc mb myminio/qr-codes --ignore-existing;
      /usr/bin/mc mb myminio/products --ignore-existing;
      /usr/bin/mc anonymous set download myminio/qr-codes;
      exit 0;
      "
    networks:
      - znak-lavki-network

  # ==============================================
  # Инструменты для разработки
  # ==============================================

  # pgAdmin для управления PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: znak-lavki-pgadmin-dev
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@znak-lavki.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - znak-lavki-network

  # Redis Commander для управления Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: znak-lavki-redis-commander-dev
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-redis123}
    depends_on:
      - redis
    networks:
      - znak-lavki-network

  # ==============================================
  # Мониторинг (опционально для dev)
  # ==============================================

  # Prometheus для сбора метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: znak-lavki-prometheus-dev
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - znak-lavki-network
    profiles:
      - monitoring

  # Grafana для визуализации метрик
  grafana:
    image: grafana/grafana:latest
    container_name: znak-lavki-grafana-dev
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - znak-lavki-network
    profiles:
      - monitoring

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  pgadmin_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  znak-lavki-network:
    driver: bridge

