# Deployment для Integration Service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: znak-lavki
  labels:
    app: integration-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
        version: v1
    spec:
      containers:
        - name: integration-service
          image: znak-lavki/integration-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: znak-lavki-config
          env:
            - name: PORT
              value: "3002"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: REDIS_PASSWORD
            - name: INTEGRATION_1C_USERNAME
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: INTEGRATION_1C_USERNAME
            - name: INTEGRATION_1C_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: INTEGRATION_1C_PASSWORD
            - name: INTEGRATION_WMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: INTEGRATION_WMS_API_KEY
          
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: znak-lavki
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: integration-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: integration-service-hpa
  namespace: znak-lavki
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: integration-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

