# Deployment для Mark Service (QR Code Service)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark-service
  namespace: znak-lavki
  labels:
    app: mark-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mark-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mark-service
        version: v1
    spec:
      containers:
        - name: mark-service
          image: znak-lavki/mark-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: http
          envFrom:
            - configMapRef:
                name: znak-lavki-config
          env:
            - name: PORT
              value: "3001"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: REDIS_PASSWORD
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: znak-lavki-secrets
                  key: MINIO_ROOT_PASSWORD
          
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
          
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mark-service
  namespace: znak-lavki
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      name: http
  selector:
    app: mark-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mark-service-hpa
  namespace: znak-lavki
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mark-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

