# Конфигурация Prometheus для development окружения

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'znak-lavki-dev'
    environment: 'development'

# Alertmanager конфигурация
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Правила алертов
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape конфигурации
scrape_configs:
  # Сам Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:3000']
        labels:
          service: 'api-gateway'
          tier: 'backend'

  # Mark Service
  - job_name: 'mark-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mark-service:3001']
        labels:
          service: 'mark-service'
          tier: 'backend'

  # Integration Service
  - job_name: 'integration-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-service:3002']
        labels:
          service: 'integration-service'
          tier: 'backend'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-service:3003']
        labels:
          service: 'notification-service'
          tier: 'backend'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          tier: 'database'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          tier: 'cache'

  # Node Exporter для мониторинга хостов
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          tier: 'infrastructure'

  # cAdvisor для мониторинга контейнеров
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          tier: 'infrastructure'

