# Prometheus Configuration for Znak Lavki

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'znak-lavki'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      timeout: 10s

# Load alert rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Mark Service - Quality mark management
  - job_name: 'mark-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mark-service:3000']
        labels:
          service: 'mark-service'
          team: 'backend'

  # API Gateway
  - job_name: 'api-gateway'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:3000']
        labels:
          service: 'api-gateway'
          team: 'backend'

  # Integration Service
  - job_name: 'integration-service'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-service:3001']
        labels:
          service: 'integration-service'
          team: 'backend'

  # Notification Service
  - job_name: 'notification-service'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-service:3002']
        labels:
          service: 'notification-service'
          team: 'backend'

  # PostgreSQL metrics
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          team: 'database'

  # Redis metrics
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          team: 'backend'

  # Node metrics (system resources)
  - job_name: 'node'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          team: 'devops'

  # Container metrics
  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          team: 'devops'

  # Alertmanager metrics
  - job_name: 'alertmanager'
    scrape_interval: 30s
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          service: 'alertmanager'
          team: 'devops'

  # Grafana metrics
  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'
          team: 'devops'
# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: 'https://your-remote-storage/api/v1/write'
#     basic_auth:
#       username: 'your-username'
#       password: 'your-password'

# Remote read configuration (optional)
# remote_read:
#   - url: 'https://your-remote-storage/api/v1/read'
#     basic_auth:
#       username: 'your-username'
#       password: 'your-password'

